### ISSUE TITLE
EXECUTION OF .py FILES

### ISSUE THREAD

**Issue by Johnaristidou** [susantoj/powerfactory_python#2]
Hello,

I am working on a project using digsilent and python like your project.

I just want to know how you execute  these python files.

Do you execute them externally through digsilent or directly from pycharm or anaconda?

To be more specific,because I am a beginner on working with digsilent, I want to execute a python file using powerfactory module directly from pycharm. If I execute my script externally or embed my code in digsilent I get results. But if I execute the script from pycharm I have to face problems with powerfactory module. This issue does not have to do with python version which I use 

Is it possible to execute a script directly through pycharm?

Looking forward to your reply
John

**Comment by peace899** [comment]
The examples in this repo are run inside PowerFactory itself. 
To execute extrenally you have to load the powerfactory module in pycharm like so:
        `import  sys`
        `sys.path.append(r'C:\Program Files\DIgSILENT\PowerFactory 2018 SP3\Python\3.6')`
        `import powerfactory as pf`

**Comment by Johnaristidou** [comment]
I have tried this with the hello world example as it is given from tutorial with no result.It understands GetApplication function but no any other method

It gives me an error on PrintPlain function.

To be more specific I want output results from a script to be printed on pycharm console.

Is this possible?
Looking forward for your reply
John

**Comment by peace899** [comment]
Can you show your code?

**Comment by Johnaristidou** [comment]
Ok I will show you 2 photos using the LineLength script from the tutorial.

The first one is from execution on pycharm where you can see that it gives me error.

The second one is from powerfactory where the script executed succesfully counting the length of lines from my project

I want those results to be printed on pycharm for further calculations



[Image]


[Image]










Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Johnaristidou** [comment]
Note that I executed this script externally in powerfactory not internally.I saved the script in powerfactory folder which is the external directory and I loaded it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peace899** [comment]
Unfortunately cannot see the images..

**Comment by Johnaristidou** [comment]
[Image]



[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Johnaristidou** [comment]
What about now? Is it ok?
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Johnaristidou** [comment]
The white one is from execution in powerfactory the other two is the code and its output on pycharm.

I hope now it will be more clearly to see them

[Image]


[Image]



[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peace899** [comment]
Still cant see, can you copy and paste your code here

**Comment by Johnaristidou** [comment]
Here is the code
import sys
sys.path.append(r'C:\Program Files\DIgSILENT\PowerFactory 2019 SP1\Python\3.7')

import powerfactory
app = powerfactory.GetApplication()
lines = app.GetCalcRelevantObjects("*.ElmLne")
length = 0
linesNr = len(lines)
for line in lines:
    length += line.dline

#option 1 (simpler and intoduce GetAttributeUnit in the second part of the exercise)
app.PrintPlain("Total length of the %i" %(linesNr) + " lines is: %.2f " %(length) + "km")
#option 2
unit = line.GetAttributeUnit('dline')
app.PrintPlain("Total length of the %i" %(linesNr) + " lines is: %.2f " %(length) + unit)

Here is the error message that I get from pycharm

Traceback (most recent call last):
  File "C:/Users/CS8675/PycharmProjects/DIGSILENT/test.py", line 6, in <module>
    lines = app.GetCalcRelevantObjects("*.ElmLne")
AttributeError: 'NoneType' object has no attribute 'GetCalcRelevantObjects'

Here is the output when I executed externally from powerfactory

info - Python Script 'Python Script(5)' started
Total length of the 45 lines is: 26572.00 km
Total length of the 45 lines is: 26572.00 m
info - Python Script 'Python Script(5)' successfully executed

Results are taken from a project inside powerfactory


________________________________

**Comment by peace899** [comment]
`Traceback (most recent call last):`
 ` File "C:/Users/CS8675/PycharmProjects/DIGSILENT/test.py", line 6, in <module>`
   ` lines = app.GetCalcRelevantObjects("*.ElmLne")`
`AttributeError: 'NoneType' object has no attribute 'GetCalcRelevantObjects'`

It means your 'app' instance does not have an active object which has GetCalcRelevantObjects', from your posted code it means you don't have an active project. You didn't activate your project.

**Comment by Johnaristidou** [comment]
I activated it and then I executed my code in pycharm.I also tested helloworld.py script where is just a printing but it executed only in powerfactory

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Johnaristidou** [comment]
Also it gives me an error for unresolved referrence to powerfactory module.The path to powerfactory module is correct but I don't know why.

In addition after import powerfactory line if I type powerfactory. I cannot see any methods or variables which it provides

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Johnaristidou** [comment]
Furthermore I noticed in tutorial guide where it says that python scripts can only be executed internally or externally only in powerfactory.


Maybe powerfactory module is not available for externally use.I mean that I cannot execute scripts using powerfactory module outside powerfactory

Am I correct?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SjorsHijgenaar** [comment]
Did you ever manage to find out how to get this working? I'm running into the same issues, only I'm using VS Code instead of PyCharm. HelloWorld script executes fine from within PowerFactory, but if I run from VS Code, I get the same

`AttributeError: 'NoneType' object has no attribute 'PrintPlain'`

Wondering if anyone has a fix for this.

**Comment by peace899** [comment]
> Did you ever manage to find out how to get this working? I'm running into the same issues, only I'm using VS Code instead of PyCharm. HelloWorld script executes fine from within PowerFactory, but if I run from VS Code, I get the same
> 
> `AttributeError: 'NoneType' object has no attribute 'PrintPlain'`
> 
> Wondering if anyone has a fix for this.

Run it directly with the interpreter by including: `if __name__ == __main__`

```
import sys
sys.path.append(PF_directory)

def main():
    #Your Code here

if __name__ == '__main__':
    import powerfactory as pf
    app = pf.GetApplication()
    main()
```

**Comment by SjorsHijgenaar** [comment]
I found out that it was working fine, but it's not possible to execute the script while an instance of PowerFactory is running. I was trying to run them simultaneously.

**Comment by Fulsur** [comment]
Hello，I execute the code in Pycharm to run PowerFactory from external.But It turns out a mirror like 
`The process has exited with exit code -1073741819 (0xC0000005: Access violation).`
Does this error have any solution?
Thank you for any help.

**Comment by peace899** [comment]
> Hello，I execute the code in Pycharm to run PowerFactory from external.But It turns out a mirror like `The process has exited with exit code -1073741819 (0xC0000005: Access violation).` Does this error have any solution? Thank you for any help.

Do you  have a sample code?

**Comment by Fulsur** [comment]
I tried another code to run PowerFactory 15.2.It succeeded.But when I change the route to run PowerFactory 2022,It fails, shows that error.

**Comment by Fulsur** [comment]
`import os
import sys
sys.path.append("C:\\Program Files\\DIgSILENT\\PowerFactory 2022\\Python\\3.10")
import powerfactory as pf


class PowerFactorySim(object):
	def __init__(self, folder_name = ' ', project_name = 'Project',
				study_case_name = 'Study Case'):                     
		self.app = pf.GetApplication();                          
		if self.app is None:
			raise Exception("getting PowerFactory application failed");
		self.app.ClearOutputWindow();
		self.app.ResetCalculation();
		self.app.ActivateProject();
		self.prj = self.app.GetActiveProject();
		#self.app.Show()

		SetDesktop = self.app.GetFromStudyCase('SetDesktop')
		SetDesktop.WriteWMF(os.getcwd() + '/Grid')

		if self.prj is None:
			raise Exception("No project activated. Python Script stopped.");
	
pfs = PowerFactorySim()`

This is a sample code.It fails.`Process finished with exit code -1073741819 (0xC0000005)`

**Comment by peace899** [comment]
I see a potential error with this line `self.app.ActivateProject();`  am surprised you didn't get an error here . The `self.app` instance is of the PF API/Application not type `IntPrj` or a project. Get the project first and the activate the project with method `ActivateProject`.

PS: You don't need semicolons after each line in Python.

**Comment by Fulsur** [comment]
It's no use to add the project name to the ActivateProject method.The same error.

**Comment by EduPython112233** [comment]
> Hello，I execute the code in Pycharm to run PowerFactory from external.But It turns out a mirror like `The process has exited with exit code -1073741819 (0xC0000005: Access violation).` Does this error have any solution? Thank you for any help.


Hi everyone, I'm having the same error.
The problem is that it's not accepting the statement:

app = pf.GetApplication()

I've been trying to find a solution for three weeks. Could you please provide some guidance on how to resolve this issue?
